### ISSUE TITLE
Histplot not working properly throughout lesson

### ISSUE THREAD

**Issue by deannagould** [learn-co-curriculum/dsc-linear-transformations#1]
## Link to Canvas

https://learning.flatironschool.com/courses/5599/assignments/196783?module_item_id=443480

## Issue Subtype

- [X] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue
histplots not working properly, throwing error
### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk
- [X] Saturn Cloud

**Comment by jessepisel** [comment]
@deannagould this issue is related to the same conflict [here](https://github.com/learn-co-curriculum/dsc-regression-assumptions-v2-5/issues/1#issuecomment-1349903014). If you follow the instructions in the `regression-assumptions` repository that will also fix this issue.
